### ISSUE TITLE
[AC Bridge With Multiplexer] If only one channel is added, it should continuously update

### ISSUE THREAD

**Issue by roboguy222** [McDermott-Group/servers#14]
Right now it waits 3*(time constant) before taking data, but if there is only one channel, it should only do this once and then start taking data ever MIN_REFRESH_INTERVAL.  This is slightly difficult because if we change the channels rapidly, so there is only one channel still, it should have to re-wait the time constant as in the beginning.

**Comment by patzinak** [comment]
This is definitely an unquestionably good idea from the software standpoint but sampling on a time scale much shorter than the time constant does not really provide a lot of information. Think of an extremely fast temperature rise — the readings simply won't be updated as fast the rise happens. However, if you have only one channel you can probably significantly reduce the time constant value because you don't really need to "forget" the transients that occurs during the channel switching. The idea is you can simply choose a notably smaller time constant when you listen to only one channel, if this is easier to implement. Again, just an idea, anything should be perfectly okay.
