### ISSUE TITLE
[ADR Server] Turn on/off FAA/GGG channels in AC Bridge w/ MP as they are selected?

### ISSUE THREAD

**Issue by roboguy222** [McDermott-Group/servers#15]
Not sure if we want this or not.  Probably depends on how regulation works when temp is updated every 10s.

**Comment by patzinak** [comment]
I am not sure whether I understand the issue but just want to clarify what reading out the GGG seems important only when the fridge is not working properly. If everything works well the GGG readings are not really important unless one day someone decide to do his/her measurements on the 500 mK finger... One way to resolve the issue is always to switch to a single channel readout mode when the fridge is being regulated. The other way is to disable the regulation button if both stages are chosen (and enable it when only one is chosen, this way one can regulate the GGG stage temperature — not that we really need this). There are likely tons of other solutions and any solution is okay as long as there is an option to monitor and log both temperatures (pseudo-)simultaneously for troubleshooting convenience.

**Comment by patzinak** [comment]
1. The server switches between FAA and GGG too fast: the temperature readings are totally unreliable. Please increase the integration time (time delay between the channel switching) and reduce/increase the time constant if necessary.
2. Somehow FAA and GGG did not work at all at some point: no errors were thrown anywhere and the AC bridge was idle (wasn't switching). Restarting the SIM rack didn't help. However, when I checked the GUI after about half an hour, the temperatures started updating.
3. The FAA/GGG checkmark boxes do not work.

**Comment by gribeill** [comment]
The ADR controller appears to work now? Restarting the SIM rack and the  FAA and GGG temperatures still take about 5 minutes to show up. This server is pretty vital and it's pretty frustrating to have to go through this every time someone updates the server. @roboguy222 , the next time you do something can you split all of the ADR control stuff into a development branch, and not merge back to the stable (usable) branch till you are sure it works?

**Comment by roboguy222** [comment]
It worked fine when I used it, so I thought it was stable.  The only real
way to tell is further use by you, but you can always revert back to the
last commit.  They do not show the temperature if it is above 20K or 45K,
depending on GGG or FAA.  That wasn't the reason it wasn't working, was it?

**Comment by patzinak** [comment]
@roboguy222 Check the log for FAA and GGG temperature for this warm-up to the room temperature. As far as I can remember, the FAA and GGG traces followed closely 3K trace and were not jumping from a couple K to 25/45K and back to a few K. Are there any other (filter?) settings that we have control over? It looks like 3 s - 10 s combination is not good enough.

**Comment by patzinak** [comment]
Looks like GGG heat sinking of the NbTi cables works pretty well, no rush with this issue for now.

**Comment by roboguy222** [comment]
Temperature seems very stable if we use a 0.3s time constant but wait 15X Tc.

**Comment by roboguy222** [comment]
With the above settings, the temperature updates fast enough that we should be able to just leave the GGG on at all times.  I am not going to implement turning it on/off.
